name: Deploy Portfolio TUI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.2.0 
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 2022
          request_pty: true   
          envs: TERM,COLORTERM
          script: |
            cd ~/portfolio-tui
            git pull origin main
            docker build -t portfolio-tui .
            
            docker stop portfolio-app || true
            docker rm -f portfolio-app || true

            docker run -d \
              --name portfolio-app \
              -p 22:2222 \
              --restart unless-stopped \
              --read-only \
              --cap-drop=ALL \
              --security-opt no-new-privileges:true \
              -e TERM=xterm-256color \
              -e COLORTERM=$COLORTERM \
              -v $(pwd)/.ssh:/home/vaishak/.ssh:ro \
              portfolio-tui